[toolchain]

[features]
resolution = true
skip-lint = true

[programs.localnet]
escrow = "EX76e8X4DtuAxWAx2w5NAoBEnVFX4nYQGRTkL3SgWDpz"
registry = "8c7pYTaDQ9A9uUjSemBsEKYu2HirduWfN5os2R6gvUAP"
aico = "8oem1ww3n2oykBo3PVpFDXjp9PQfE9efWysL7oDCKNEE"

[programs.devnet]
escrow = "EX76e8X4DtuAxWAx2w5NAoBEnVFX4nYQGRTkL3SgWDpz"
registry = "2UFmTxSgoRMkNhLUcs8ytnYcTbcEXNiA9EzW7BMqika3"
aico = "8oem1ww3n2oykBo3PVpFDXjp9PQfE9efWysL7oDCKNEE"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Devnet"
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
client = "yarn run ts-node client/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
