[toolchain]

[features]
resolution = true
skip-lint = true

[programs.localnet]
escrow = "4JGo2qhxDy4gXi7PXVAiAeaTUWKwK8cnfTNJwSpsQQ8Q"
leea-agent-registry = "AtKE5SswVK3f5pw8uQjH8C4irYKZNweAmc7UU1GgcaRa"
leea-token = "6KrePYF8rLwkukByMsqMXgi8d83U8fn83MzVMeXgUXag"

[programs.devnet]
leea-agent-registry = "AtKE5SswVK3f5pw8uQjH8C4irYKZNweAmc7UU1GgcaRa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
client = "yarn run ts-node client/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
