name: Compile client-rs
on: push

env:
  CARGO_INCREMENTAL: 0

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [
          x86_64-pc-windows-gnu,
          x86_64-unknown-linux-musl,
          aarch64-apple-darwin,
          x86_64-apple-darwin
        ]
    steps:
      - uses: actions/checkout@master
      - name: Rustup!
        run: rustup update
      - name: Compile
        working-directory: contracts/solana
        run: cargo build --release --target ${{ matrix.target }}
#      - name: Compile and release
#        uses: rust-build/rust-build.action@v1.4.5
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          RUSTTARGET: ${{ matrix.target }}
##          EXTRA_COMMAND_FLAGS: "--bin registry-client --release"
#          SRC_DIR: "contracts/solana"
